import { RuleStore } from '../rule';
export declare const required: RuleStore['required'];
export declare const empty: RuleStore['empty'];
export declare const regexp: RuleStore['regexp'];
export declare const email: RuleStore['email'];
export declare const list: RuleStore['list'];
export declare const number: RuleStore['number'];
export declare const integer: RuleStore['integer'];
export declare const naturalNumber: RuleStore['naturalNumber'];
export declare const positiveNumber: RuleStore['positiveNumber'];
export declare const negativeNumber: RuleStore['negativeNumber'];
export declare const zero: RuleStore['zero'];
export declare const age: RuleStore['age'];
